# Generate a C source embedding a binary font file as a byte array.
#   cmake -DFONT_IN=<ttf> -DOUT_C=<out.c> -P embed_font.cmake
# Produces:  const unsigned char g_hudFontData[]; const unsigned int g_hudFontDataSize;
# Run via add_custom_command so it regenerates only when the TTF changes.

file(READ "${FONT_IN}" _hex HEX)
string(LENGTH "${_hex}" _n)
math(EXPR _count "${_n} / 2")
# "ab" -> "0xab," for every byte.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")

file(WRITE "${OUT_C}"
"/* Generated by cmake/embed_font.cmake — do not edit. Source: LiberationMono-Regular.ttf (OFL). */\n"
"const unsigned char g_hudFontData[] = {${_body}};\n"
"const unsigned int  g_hudFontDataSize = ${_count};\n")
